Feat/me 44 set up database
nic5694/MovingExpress pull request #2
Opened 2023-11-28 23:03 UTC by RichardDanon

JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/ME-44?atlOrigin=eyJpIjoiMjI1OTM2MDViNTg3NGMwODk3ZDdhZWYzODRhMjVjYWYiLCJwIjoiaiJ9)

## Context:

This ticket outlines the requirement for an automated system to initialize and configure the database environment, aiming to provide a consistent and ready-for-development setup.

## Changes

1. Updated the docker-compose file
2. Created the application.yml file
3. Created the schema-mysql.sql

## Dev notes (Optional)
- This is simply a setup so that the backend can operate properly

2023-11-28 23:26 UTC, nic5694 approved these changes
please review the changes in suggested, overall good. Only small details that i feel will reflect better the domain

2023-11-28 23:26 UTC, nic5694 commented on backend/build.gradle
> +                minimum = 0.00
please dont forget to place it back to 90% after your done the tests

2023-11-28 23:26 UTC, nic5694 commented on backend/src/main/resources/schema-mysql.sql
> +    type ENUM('Item', 'BOX') NOT NULL,
i think it should both be in pairal letters because their final so ITEM, BOX

2023-11-28 23:26 UTC, nic5694 commented on backend/src/main/resources/schema-mysql.sql
> +    picture BLOB,
we should see if we should store the inages on a seperate database and just hold the link in the mysql

2023-11-28 23:26 UTC, nic5694 commented on backend/src/main/resources/schema-mysql.sql
> +    movingCrewId VARCHAR(36),
you should add the foreign key references
FOREIGN KEY REFERENCES(...)

2023-11-28 23:26 UTC, nic5694 commented on backend/src/main/resources/schema-mysql.sql
> +    movingCrewId VARCHAR(36),
like you've done below

2023-11-28 23:31 UTC, RichardDanon commented on backend/src/main/resources/schema-mysql.sql
> +    type ENUM('Item', 'BOX') NOT NULL,
Alright makes sense. I'll change it right now

2023-11-28 23:42 UTC, RichardDanon commented on backend/src/main/resources/schema-mysql.sql
> +    picture BLOB,
Yeah.. that might be a better option to save storage. Noted!

2023-11-28 23:46 UTC, liu-cal approved these changes
Containers were well set up, database table columns' datatypes were right, just some of the columns were missing, but overall, configurations and profiles were correct.

2023-11-28 23:48 UTC, RichardDanon commented on backend/src/main/resources/schema-mysql.sql
> +    email VARCHAR(255),
True true

2023-11-28 23:52 UTC, RichardDanon commented on backend/src/main/resources/schema-mysql.sql
> +    capacity INT
it's better to change it to a double for now and see later on I think because it's harder to regulate what people can input in a varchar.

2023-11-28 23:56 UTC, RichardDanon commented on backend/src/main/resources/schema-mysql.sql
> +    email VARCHAR(255)
On it

2023-11-29 04:45 UTC, Youssefchahboune requested changes
Please review everything I wrote. I have more questions for you, but let's discuss them in person tomorrow.

2023-11-29 04:45 UTC, Youssefchahboune commented on backend/src/main/resources/schema-mysql.sql
> +    picture BLOB,
I taught we were not doing images ?

2023-11-29 04:45 UTC, Youssefchahboune commented on backend/src/main/resources/schema-mysql.sql
> +    type ENUM('ITEM', 'BOX','ITEMS','BOXES') NOT NULL,
Why is there "Items" and "Boxes" as type ??  an item can be either a box or a singular item not multiple items or boxes ?

2023-11-29 04:45 UTC, Youssefchahboune commented on backend/src/main/resources/schema-mysql.sql
> +CREATE TABLE IF NOT EXISTS Item (
You are missing itemName as a field like i understand there's description but we still need an item name

2023-11-29 04:45 UTC, Youssefchahboune commented on backend/src/main/resources/schema-mysql.sql
> +CREATE TABLE IF NOT EXISTS Item (
you are also missing item weight but this field can be null

2023-11-29 04:45 UTC, Youssefchahboune commented on backend/src/main/resources/schema-mysql.sql
> +    pickUpLocation VARCHAR(50),
For pickuplocation and dropoffdestination  you are missing building type and number of rooms

2023-11-29 04:45 UTC, Youssefchahboune commented on backend/src/main/resources/schema-mysql.sql
> +CREATE TABLE IF NOT EXISTS MovingCrew (
Why do we have a moving crew if our system doesn't manage it? Where are we going to display or view the moving crew?

2023-11-30 16:17 UTC, RichardDanon commented on backend/src/main/resources/schema-mysql.sql
> +    type ENUM('ITEM', 'BOX','ITEMS','BOXES') NOT NULL,
Mhhm alright on it

2023-11-30 16:18 UTC, RichardDanon commented on backend/src/main/resources/schema-mysql.sql
> +CREATE TABLE IF NOT EXISTS Item (
I though i did thanks for letting me know man

2023-11-30 16:18 UTC, RichardDanon commented on backend/src/main/resources/schema-mysql.sql
> +CREATE TABLE IF NOT EXISTS Item (
Got it

2023-11-30 16:55 UTC, liu-cal approved these changes
All tables contain relevant and adequate attributes. Overall, the schema is well-written.

2023-11-30 16:55 UTC, liu-cal commented on backend/src/main/resources/schema-mysql.sql
> +    weight DOUBLE NULL,
Similar to the capacity attribute in the truck table, later on since the weight could be in kg or lbs, this could be changed to a string
```suggestion
    weight VARCHAR(5) NULL,
```

2023-11-30 16:57 UTC, merged